include: package:flutter_lints/flutter.yaml


linter:
  rules:
    # Error Rules.
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    cancel_subscriptions: true
    close_sinks: true
    invariant_booleans: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    prefer_relative_imports: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    use_build_context_synchronously: true
    # Style Rules.
    always_declare_return_types: true
    avoid_positional_boolean_parameters: true
    avoid_returning_null: true
    avoid_returning_this: true
    avoid_types_on_closure_parameters: true
    avoid_void_async: true
    directives_ordering: true
    flutter_style_todos: true
    join_return_with_assignment: true
    missing_whitespace_between_adjacent_strings: true
    omit_local_variable_types: true
    one_member_abstracts: true
    prefer_asserts_in_initializer_lists: true
    prefer_constructors_over_static_methods: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_foreach: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_int_literals: true
    prefer_interpolation_to_compose_strings: true
    prefer_mixin: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    unawaited_futures: true
    unnecessary_lambdas: true
    unnecessary_null_aware_assignments: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_named_constants: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_to_and_as_if_applicable: true
    sort_pub_dependencies: true
    # Override Rules.
    use_key_in_widget_constructors: false
