name: manga_reader
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  get: ^4.6.5
  get_storage: ^2.0.3
  path: ^1.8.2
  path_provider: ^2.0.11
  permission_handler: ^10.0.2
  photo_view: ^0.14.0

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1


flutter_icons:
  android: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
